package com.kern.launcher.model

sealed class Command {
    data class AppLaunch(val app: AppInfo) : Command()
    data class GoogleSearch(val query: String) : Command()
    data class GoogleMaps(val query: String) : Command()
    data class YoutubeSearch(val query: String) : Command()
    data class SpotifySearch(val query: String) : Command()
    data class PlayStoreSearch(val query: String) : Command()
    data class GithubSearch(val query: String) : Command()
    data class WikipediaSearch(val query: String) : Command()
    data class RedditSearch(val query: String) : Command()
    data class TwitterSearch(val query: String) : Command()
    data class DuckDuckGoSearch(val query: String) : Command()
    data class AiSearch(val prompt: String, val provider: String = "CHATGPT") : Command()
    data class LazyLogsAdd(val rawText: String) : Command()
    data class DeepLinkUri(val uriString: String, val label: String) : Command()
    data class Calculator(val expression: String, val result: String) : Command()
    data class Timer(val durationSeconds: Int, val rawInput: String) : Command()
    data class HideApp(val app: AppInfo) : Command()
    data class UnhideApp(val packageName: String, val label: String) : Command()
    data class AppInfoSettings(val packageName: String, val appLabel: String) : Command()
    data object ShowHiddenApps : Command()
    data object ToggleTuiView : Command()
    data object OpenSettings : Command()
    data object Help : Command()
    data class CustomAlias(val alias: String, val resolvedCommand: Command) : Command()
    data class Unknown(val rawQuery: String) : Command()
}
